package postgres_test

import (
	"reflect"
	"testing"

	"github.com/DaiYuANg/arcgo/dbx"
	postgres "github.com/DaiYuANg/arcgo/dbx/dialect/postgres"
	"github.com/stretchr/testify/require"
)

func TestBuildCreateTable(t *testing.T) {
	bound, err := postgres.New().BuildCreateTable(dbx.TableSpec{
		Name: "users",
		Columns: []dbx.ColumnMeta{
			{Name: "id", Table: "users", GoType: reflect.TypeFor[int64](), PrimaryKey: true, AutoIncrement: true},
			{Name: "username", Table: "users", GoType: reflect.TypeFor[string]()},
			{Name: "email_address", Table: "users", GoType: reflect.TypeFor[string]()},
			{Name: "role_id", Table: "users", GoType: reflect.TypeFor[int64]()},
			{Name: "status", Table: "users", GoType: reflect.TypeFor[int]()},
		},
		PrimaryKey: &dbx.PrimaryKeyMeta{
			Name:    "pk_users",
			Table:   "users",
			Columns: []string{"id"},
		},
		ForeignKeys: []dbx.ForeignKeyMeta{
			{
				Name:          "fk_users_role_id",
				Table:         "users",
				Columns:       []string{"role_id"},
				TargetTable:   "roles",
				TargetColumns: []string{"id"},
				OnDelete:      dbx.ReferentialCascade,
			},
		},
		Checks: []dbx.CheckMeta{
			{
				Name:       "ck_users_status",
				Table:      "users",
				Expression: "status >= 0",
			},
		},
	})
	require.NoError(t, err)

	expected := `CREATE TABLE IF NOT EXISTS "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "username" TEXT NOT NULL, "email_address" TEXT NOT NULL, "role_id" BIGINT NOT NULL, "status" INTEGER NOT NULL, CONSTRAINT "fk_users_role_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE, CONSTRAINT "ck_users_status" CHECK (status >= 0))`
	require.Equal(t, expected, bound.SQL)
}

func TestInspectTable(t *testing.T) {
	// InspectTable issues Postgres-specific information_schema / pg_catalog queries; it cannot run against SQLite.
	t.Skip("InspectTable requires real postgres")
}
